### ISSUE TITLE
No optimization effects (pending changes in Perseus)

### ISSUE THREAD

**Issue by phaleth** [arctic-hen7/perseus-size-opt#1]
Today, I've noticed this new plugin and also the `simple` example this repo holds, which I've tried to deploy with the `Dockerfile` bellow. Notice that there is no `wee_alloc` or other sort of manual optimization in place.

Dockerfile
```Dockerfile
# get the base image
FROM rust:1.55-slim AS build

# install build dependencies
RUN apt update \
  && apt install -y --no-install-recommends lsb-release apt-transport-https \
  build-essential curl

# prepare root project dir
WORKDIR /app

# download the target for wasm
RUN rustup target add wasm32-unknown-unknown

# install wasm-pack
RUN cargo install wasm-pack

# retrieve the src dir
RUN curl https://codeload.github.com/arctic-hen7/perseus-size-opt/tar.gz/main | tar -xz --strip=2 perseus-size-opt-main/examples/simple

# go to src dir
WORKDIR /app/simple

# install perseus-cli
RUN cargo install perseus-cli --version 0.3.0-beta.13

# clean app
RUN perseus clean

# adjust app config
RUN sed -i s'/perseus = .*/perseus = "0.3.0-beta.13"/' ./Cargo.toml \
  && sed -i s'/perseus-size-opt = .*/perseus-size-opt = "0.1.0"/' ./Cargo.toml \
  && cat ./Cargo.toml

# modify and prepend lib.rs
RUN sed -i s'/"Hello World!"/"世界您好 !"/' ./src/lib.rs \
  && cat ./src/lib.rs

# prep app
RUN perseus prep

# adjust and append perseus config
RUN sed -i s'/perseus = .*/perseus = "0.3.0-beta.13"/' .perseus/Cargo.toml \
  && cat .perseus/Cargo.toml

# deploy app
RUN perseus deploy

# prepare deployment image
FROM bitnami/minideb:buster

WORKDIR /app

COPY --from=build /app/simple/pkg /app/

ENV PERSEUS_STANDALONE=true

ENV HOST=0.0.0.0

CMD ["./server"]
```

The result is that the plugin isn't doing any optimization at all. Bellow is a picture of a browser with network tab opened.

![plugin-not-optimizing](https://user-images.githubusercontent.com/29838606/138163149-2f69f1b3-a194-4987-b0fe-275460be8934.png)

As always the `Dockerfile` above is standalone.

I can provide more feedback if needed, but right now I think this plugin does not add much value. For the most part I do like the way this plugin is headed, but I'd highly recommend leaving it aside at least for the time being until optimizations for production becomes a necessity to deal with for a broader Perseus userbase.

The reason for the above statement is that I've noticed optimizations of the `bundle.wasm` size I've managed to do lately seem to add pretty much questionable value. I've noticed that those optimizations affect not only the client side `bundle.wasm` size, but also shrink the size of the `server` binary deployed on the server, which should not be desired. Not sure if the aim of this plugin is to do any different and leave the server side bundle unoptimized.

**Comment by arctic-hen7** [comment]
Haha you beat me to opening this! I'm aware that currently this plugin actually *increases* binary size in some cases, and that will be fixed by the issue of feature-gating in Perseus. Because this plugin only uses the `tinker` action, you don't actually need plugins enabled to use it (`perseus tinker` will manage that for you), so after that issue is closed, this plugin should have major effects! That said, if you apply it on the Perseus website without running `perseus tinker`, the binary size goes up to 1.5MB, and after running `perseus tinker`, it goes down to 1.2MB, so the fault is definitely in the core package rather than here I think.
